### ISSUE TITLE
dddmp support_vars

### ISSUE THREAD

**Issue by stephanietsuei** [tulip-control/dd#14]
Support variable names in dddmp headers is an optional field in dddmp 2.0 files. As of now, `dddmp.py` will crash at lines 267 and 202-203.

**Comment by johnyf** [comment]
This appears to refer to [conditional dump](https://github.com/johnyf/cudd/blob/80c9396b7efcb24c33868aeffb89a557af0dc356/cudd/dddmp/dddmpStoreBdd.c#L425) of variable names by DDDMP, and the option [`DDDMP_VARIDS`](https://github.com/johnyf/cudd/blob/80c9396b7efcb24c33868aeffb89a557af0dc356/cudd/dddmp/dddmpStoreBdd.c#L358). I have found it easier and more dependable to tell DDDMP to dump variable names, for example as it is done [here](https://github.com/johnyf/slugs/blob/synt_2015/src/BFAbstractionLibrary/BFCuddManager.cpp#L178). I was aware that `dddmp.py` does not cover all DDDMP configuration cases.

If dumping variable (string) names is not an option, and this is a feature request to support every configuration of DDDMP, then I do not know when or whether it will be implemented (pull requests are welcome). The main reason is that DDDMP's [documentation](http://www.swi-prolog.org/pack/file_details/trill/cudd-2.5.1/dddmp/doc/dddmp-2.0-A4.ps) is *very* difficult to understand, if not logically inconsistent and missing information. When I wrote `dddmp.py`, I had spent a day trying to understand the document. Eventually I gave up, and read [DDDMP's code](https://github.com/johnyf/cudd/tree/80c9396b7efcb24c33868aeffb89a557af0dc356/cudd/dddmp), from where it was much easier to infer what the format means, in an hour.

After the above experience, it is much easier and more dependable to write a little C or Cython function that recursively dumps the BDD from CUDD to a `json` file with proper naming of variable names and levels (and no mystical `*ids` of all sorts), than to spend time with DDDMP. Loading can then be done with an incremental parser (BDD files can run into the GBs) like [`ijson`](https://github.com/isagalaev/ijson) or [`json-streamer`](https://github.com/kashifrazzaqui/json-streamer), and nobody will ever again need to write any custom loader for CUDD results, nor read any documentation to understand what the fields mean.

Also, please note that [DDDMP erases the unique table](https://github.com/johnyf/cudd/blob/80c9396b7efcb24c33868aeffb89a557af0dc356/cudd/dddmp/dddmpStoreBdd.c#L82) and invalidates the caches, thus destroying all hashing effort and memoization up to then, in case further processing is to follow.

**Comment by slivingston** [comment]
@johnyf Is there a JSON dumper and loader that is compatible with CUDD?

DDDMP is under a restrictive license, so moving away from it is motivated for the sake of freedom, in addition to the technical motivations that you give.

**Comment by johnyf** [comment]
Not that I know of, nor that I can find through a search. My impression from the existing tooling around, people don't use BDDs very much for data persistence. Instead, circuits in BLIF, AIGER, or other formats are dumped by the communities mostly using BDDs in their algorithms.

So, I think that we should write one. Earlier comments on this pursuit: https://github.com/johnyf/dd/issues/10#issuecomment-191695313

**Comment by stsuei** [comment]
Hello! I filed this bug report thinking that you had intended to support all features of DDDMP while I was fiddling with dd.

I am indeed interested in using BDDs for data persistence, but probably don't need dd. I could give you a very inelegant pull request for this specific feature, but it seems that we're all content the way things are now.

**Comment by johnyf** [comment]
The lines mentioned [above](https://github.com/tulip-control/dd/issues/14#issue-170268197) are

https://github.com/tulip-control/dd/blob/v0.4.0/dd/dddmp.py#L202-L203

and

https://github.com/tulip-control/dd/blob/v0.4.0/dd/dddmp.py#L267

Closed in commit 5e4c6c9785c6f5867b5ae481579af5123dc08284.

Also, JSON dumping and loading (discussed above) has been implemented in the module `dd._copy`:

https://github.com/tulip-control/dd/blob/v0.5.5/dd/_copy.py#L85-L89

and

https://github.com/tulip-control/dd/blob/v0.5.5/dd/_copy.py#L153-L158

JSON is available to dump and load BDDs in `dd.cudd` and `dd.autoref` after dc4ee404dd072460934c3aea86c9ed409946981b and 35871a3b21cea2be6ab9d094249920fc785de50d.
