### ISSUE TITLE
Checking queries where variable is True

### ISSUE THREAD

**Issue by random-novice** [tulip-control/dd#38]
Hey

This is a beginner level question. 
From a bdd, how can you extract the possible queries where a particular variable is TRUE/FALSE. 
Right now I have a list of variables and I generate the BDD. 
Not quite sure how to retrieve the queries for the cases where a variable is TRUE and FALSE. 

Thanks in advance for your help

Cheers,
Chris

**Comment by slivingston** [comment]
Did you read the [documentation file dd/doc.md](https://github.com/johnyf/dd/blob/master/doc.md), in particular [the section about reachability analysis](https://github.com/johnyf/dd/blob/master/doc.md#example-reachability-analysis) ?

**Comment by slivingston** [comment]
If I understand your question correctly, then the method of interest is `pick_iter`. For example, consider the formula

    x & y

(also can be written as `x /\ y`). To find all elements in the support set for which `x = TRUE`, then
```python
from dd import autoref as _bdd

bdd = _bdd.BDD()
bdd.declare('x', 'y')

u = bdd.add_expr('x | y')

u_x_fixed = u & bdd.add_expr('x')

print(list(bdd.pick_iter(u_x_fixed, care_vars=['x', 'y'])))
```
For the case of `x = FALSE`, instead use `u_x_fixed = u & bdd.add_expr('!x')`.

**Comment by slivingston** [comment]
@random-novice given no response and because I think that the example above addresses the original post, I am closing this issue. Please re-open it if needed.
