### ISSUE TITLE
Forming incorrect BDD

### ISSUE THREAD

**Issue by rahulguptakota** [tulip-control/dd#39]
Wouldn't the rule that "only an “else” branch can be negated, signified by a -1 annotation" handicap the power to form BDD for certain clauses.
For instance,
BDD for 
p cnf 1 1
1 0
and 
p cnf 1 1
-1 0
is shown to be the same by this tool which is obviously not the case and it seems that former example is incorrectly drawn by dd.
[new.pdf](https://github.com/tulip-control/dd/files/2226765/new.pdf)

**Comment by johnyf** [comment]
External references to BDDs can be negated when using the classes `dd.cudd.BDD`, `dd.sylvan.BDD`, `dd.autoref.BDD`, and `dd.bdd.BDD`. The "positive" version of each Boolean function is represented by a node in the BDD manager. The user creates references to these nodes. A reference can be negated (complemented) or not, similarly to how edges within the BDD manager can be complemented or not.

The PDF `new.pdf` [above](https://github.com/tulip-control/dd/issues/39#issue-344310601) can be created with the following code

```python
from dd import autoref as _bdd

bdd = _bdd.BDD()
bdd.declare('x1')
u = bdd.add_expr('x1')
not_u = bdd.add_expr(' ~ x1 ')
>>> print(u)
print(not_u)
bdd.dump('new.pdf', roots=[not_u])
```

The two references `u` and `not_u` correspond to the given conjunctive normal forms (CNFs). These references are external to the BDD manager. The references `u` and `not_u` can be distinguished by checking whether they are negated:

```python
>>> print(u.negated)
False
>>> print(not_u.negated)
True
>>> print(u)
@2
>>> print(not_u)
@-2
```

where the integers are the nodes in the underlying instance of the class `dd.bdd.BDD` that implements the class `dd.autoref.BDD`. The reference `u` is the top node (indexed by 2) in the plotted diagram. The reference `not_u` is a negated edge to the top node (represented by -2).

This issue suggests adding to the function `dd.bdd.to_pydot` plotting of nodes that represent external BDD references, to make evident whether these references are negated or not.
Each such "external ref" node could be labeled with `@INT` or `@-INT` (for negated references).
