### ISSUE TITLE
best links for CUDD ?

### ISSUE THREAD

**Issue by slivingston** [tulip-control/dd#48]
The original reference URL for CUDD, <http://vlsi.colorado.edu/~fabio/CUDD/>, is valid no more. Does anyone know of a preferred alternative?

There are various copies of the CUDD API documentation and code hosted around the Web, but I did not find one that is ordained by Fabio (the original author of CUDD).

One idea is to link to the most recent snapshot of <http://vlsi.colorado.edu/~fabio/CUDD/> on the Internet Archive,
<https://web.archive.org/web/20180127051756/http://vlsi.colorado.edu/~fabio/CUDD/html/index.html>, which is just the Doxygen-generated API documentation for CUDD v3. This might be usefully supplemented by a link to the documentation as of version 2.5, which has a more welcoming introduction at
<https://web.archive.org/web/20150317121927/http://vlsi.colorado.edu/~fabio/CUDD/node1.html>

**Comment by johnyf** [comment]
I agree with linking also to the archived version of the documentation, possibly keeping the original link in case it becomes reachable.

**Comment by slivingston** [comment]
To keep all of these useful links, I propose that the README is changed as
```diff
diff --git a/README.md b/README.md
index be8e9e8..185f731 100644
--- a/README.md
+++ b/README.md
@@ -12,7 +12,7 @@ A pure-Python (3 and 2) package for manipulating:
 
 as well as [Cython](http://cython.org/) bindings to the C libraries:
 
-- [CUDD](http://vlsi.colorado.edu/~fabio/CUDD/)
+- [CUDD](https://web.archive.org/web/20180127051756/http://vlsi.colorado.edu/~fabio/CUDD/html/index.html) (also read [the introduction](https://web.archive.org/web/20150317121927/http://vlsi.colorado.edu/~fabio/CUDD/node1.html), and note that the original link for CUDD is <http://vlsi.colorado.edu/~fabio/CUDD/>)
 - [Sylvan](https://github.com/utwente-fmt/sylvan) (multi-core parallelization)
 - [BuDDy](https://sourceforge.net/projects/buddy/)
```
which as rendered HTML appears as
> [CUDD](https://web.archive.org/web/20180127051756/http://vlsi.colorado.edu/~fabio/CUDD/html/index.html) (also read [the introduction](https://web.archive.org/web/20150317121927/http://vlsi.colorado.edu/~fabio/CUDD/node1.html), and note that the original link for CUDD is <http://vlsi.colorado.edu/~fabio/CUDD/>)

**Comment by johnyf** [comment]
I agree with this change.
