### ISSUE TITLE
Help installing the python Sylvan wrapper 

### ISSUE THREAD

**Issue by glarange** [tulip-control/dd#52]
Hi,
Sorry, not an issue, more question. How do I install the Sylvan wrapper?
Thanks
Gui

**Comment by johnyf** [comment]
One way to build Sylvan and the Cython module `dd.sylvan` is as done in the file `.travis.yml`:

https://github.com/tulip-control/dd/blob/f9aa4d1a09c286de769bde17dd92ece63cf4c3d9/.travis.yml#L28-L40

If building only Sylvan, the last line can be `python setup.py install --sylvan`.

Using `cython>=0.29.15` to build `dd.sylvan` requires `dd >=` a5948d84ea031420c44649b8286dfc6cbb9dd2b5 from the repository (the latest PyPI release is `dd == 0.5.5` and requires an earlier Cython version when building `dd.sylvan`).
