### ISSUE TITLE
Same code works with pure python (dd import autoref as _bdd) but not dd.cudd

### ISSUE THREAD

**Issue by moohtuh** [tulip-control/dd#54]
From what I understand I may not be using the _bdd.add_expr_ correctly or it might be naming the bdd :

This is an example line : 
**expression** ='!a&!b&c&d | !a&b&!c&d'  ---Example---

a = bdd.add_expr( **expression** )   ---ERROR HERE---
b = bdd.add_expr( **expression** )
z = a & b

I have newly installed the comprehensive cudd version as I need to work with zdd and working in Spyder IDE. This is the error I get when I try to run the same code that works with pure python version:  https://ibb.co/yWbfRtW

Any advice please?

**Comment by johnyf** [comment]
This is an error from `ply.lex` that occurs inside the pure Python module [`dd._parser`](https://github.com/tulip-control/dd/blob/f9aa4d1a09c286de769bde17dd92ece63cf4c3d9/dd/_parser.py#L202) when the function `dd._parser.add_expr` is called from the method `dd.cudd.BDD.add_expr`. The required version of [`ply`](https://github.com/dabeaz/ply/) is:

https://github.com/tulip-control/dd/blob/f9aa4d1a09c286de769bde17dd92ece63cf4c3d9/setup.py#L48

This version of `ply` can be installed with `pip install ply==3.10`. The installed version of `ply` can be found with `pip show ply`.

Another point to ensure is that `ply` is installed when building `dd`, i.e., before running `python setup.py install --cudd`, and that `pip uninstall -y dd` is run to uninstall all previously installed versions of `dd`, before reinstalling `dd`.

**Comment by moohtuh** [comment]
I followed your instruction. Now there's a different error.  I see both graphviz and pydot installed. I do not understand what I have done wrong here-https://ibb.co/ZcJYnVD

**Comment by johnyf** [comment]
`sudo apt install graphviz` is expected to install the executable file `dot`, as described [here](https://www.graphviz.org/download/). To confirm whether `dot` has been installed and can be found on the `PATH`, the command `which dot` could be used.

The Python package `graphviz` does not install [GraphViz](https://en.wikipedia.org/wiki/Graphviz) (and `dot`), so `pip install graphviz` has no effect on whether `pydot` works.

`pydot-ng` is a fork of `pydot`, not needed to run `pydot`.

It seems that indeed `pydot` is installed, but it cannot find GraphViz's file `dot` in the `PATH`. `pydot` is a Python package that interfaces to the executable programs that GraphViz installs.
