### ISSUE TITLE
implement method `dd.sylvan.BDD.pick_iter`

### ISSUE THREAD

**Issue by glarange** [tulip-control/dd#55]
Hi Johnny,

I was able to use pick.iter in dd.cudd but not in the dd.sylvan. Any suggestions would be much appreciated. Thanks again! Gui

![Capture_sylvan_not_implemented](https://user-images.githubusercontent.com/3644658/85092740-5cf6d300-b1b8-11ea-9e2d-8aaf61642cf1.PNG)

**Comment by johnyf** [comment]
The method `dd.sylvan.BDD.pick_iter` has not been implemented as of f9aa4d1a09c286de769bde17dd92ece63cf4c3d9. The exception `NotImplementedError` is documented [here](https://docs.python.org/3/library/exceptions.html#NotImplementedError).

https://github.com/tulip-control/dd/blob/f9aa4d1a09c286de769bde17dd92ece63cf4c3d9/dd/sylvan.pyx#L293-L296

An implementation would be similar to `dd.cudd.BDD.pick_iter`:

https://github.com/tulip-control/dd/blob/f9aa4d1a09c286de769bde17dd92ece63cf4c3d9/dd/cudd.pyx#L906-L946

taking into account how `sylvan_low` works:

https://github.com/tulip-control/dd/blob/f9aa4d1a09c286de769bde17dd92ece63cf4c3d9/dd/sylvan.pyx#L557

**Comment by johnyf** [comment]
Addressed in 3cca74c9dd94be451b0d3dc82dca2752414b34fe.
