### ISSUE TITLE
Enhancement suggestion: fast BDD algorithm for large coherent fault trees 

### ISSUE THREAD

**Issue by glarange** [tulip-control/dd#56]
Hi @johnyf @slivingston 

Any interest in implementing a slightly modified but much faster BDD when the boolean function is "coherent"?
If not, could you point me in the direction of the function where I could attempt this myself?

Thanks
G
[a fast BDD algorithm for large coherent fault trees analysis.pdf](https://github.com/tulip-control/dd/files/4807876/a.fast.BDD.algorithm.for.large.coherent.fault.trees.analysis.pdf)

**Comment by slivingston** [comment]
@glarange Is this still of interest to you?

I am catching up on issues and missed this one. If you closed it out of frustration, please re-open, and we can discuss it.
