### ISSUE TITLE
Assignment of BDD/ ZDD

### ISSUE THREAD

**Issue by moohtuh** [tulip-control/dd#57]
1. If I use `from dd.cudd_zdd import ZDD as BDD` in the beginning of a code does that mean all the subsequent computations will calculate ZDD? Even bdd.dump will dump ZDD?

2.  Here is my code:

```
declaredvariables=['a','b','c' ]
iteration 
declaredvariables[index]=bdd.add_expr(expression)
```

At the very end, I want to calculate a combined bdd and zdd both so:

```
combined = a & b & c
bdd.dump(' ', combined)
zdd.dump(' ', combined)
```

However, I see that after executing the first part of the code all indexes of declaredvariables[index] are changed to some numbers like @94046918771 @94046918667 @9404698931

If I do this will it work:

`combined = declaredvariables[0] & declaredvariables[1]  & declaredvariables[2] `

**Comment by johnyf** [comment]
`from dd.cudd_zdd import ZDD` will import a ZDD manager. With `zdd = ZDD()` all computations related to the instance `zdd` will be performed using ZDDs. BDD computations can be performed alongside the ZDD computations, in a BDD manager. For example:

```python
from dd.cudd import BDD
from dd.cudd_zdd import ZDD

bdd = BDD()  # instance of BDD manager
zdd = ZDD()  # instance of ZDD manager

bdd.declare('x', 'y')  # declaring variable identifiers x and y in the BDD manager `bdd`
u = bdd.add_expr('x /\ y')  # creating the BDD of the Boolean function `x /\ y` (the conjunction of variables x and y)

zdd.declare('x', 'y')  # declaring variable identifiers x and y in the ZDD manager `zdd`
v = zdd.add_expr('x /\ y')  # creating the BDD of the Boolean function `x /\ y`
```

The BDD and ZDD computations are in separate managers. To perform any computation between Boolean functions represented with BDDs and ZDDs, first either:
- the BDDs would need to be converted to ZDDs, or
- the ZDDs would need to be converted to BDDs. For example:

```python
u_zdd = bdd.copy(u, zdd)  # copying BDD with root `u` to a ZDD with root `u_zdd`
assert u_zdd == v, (u_zdd, v)  # the result equals ZDD `v` because both ZDDs represent the Boolean function `x /\ y`

v_bdd = zdd.copy(v, bdd)  # copying ZDD with root `v` to a BDD with root `v_bdd`
assert v_bdd == u, (v_bdd, v)  # the result equals BDD `u` because both BDDs represent the Boolean function `x /\ y`
```

The copying methods `dd.cudd.BDD.copy` and `dd.cudd_zdd.ZDD.copy` use functions from the module `dd._copy`. So the above copying calls are equivalent to:

```python
from dd import _copy

u_zdd = _copy.copy_bdd(u, zdd)
v_bdd = _copy.copy_zdd(v, bdd)
```

Details of these functions:

https://github.com/tulip-control/dd/blob/f9aa4d1a09c286de769bde17dd92ece63cf4c3d9/dd/_copy.py#L33-L38

https://github.com/tulip-control/dd/blob/f9aa4d1a09c286de769bde17dd92ece63cf4c3d9/dd/_copy.py#L84-L89

The method `zdd.dump` will create a PDF file of the graph of the given ZDD nodes (the nodes reachable from the given roots). This is the method `dd.cudd_zdd.ZDD.dump`, with code:

https://github.com/tulip-control/dd/blob/f9aa4d1a09c286de769bde17dd92ece63cf4c3d9/dd/cudd_zdd.pyx#L1601-L1615

The method `dd.cudd.BDD.dump` and the method `dd.autoref.BDD.dump` will still dump BDDs. Please note that the plots of a BDD and a ZDD look different with the current implementation of plotting (even with more similar plotting implementations, still the graphs of the BDD representation and of the ZDD representation for the same Boolean function are different).

About infix operators between instances of the class `dd.cudd_zdd.Function` (the method `dd.cudd_zdd.ZDD.add_expr` returns instances of this class), they can be applied as follows:

```python
x = zdd.add_expr('x')
y = zdd.add_expr('y')

x_and_y = x & y
x_or_y = x | y
```

A `list` could be used to store `Function` instances.

The `@`-prefixed numbers are the string representation of BDD references, and of ZDD references. They are described in [this section of the documentation](https://github.com/tulip-control/dd/blob/f9aa4d1a09c286de769bde17dd92ece63cf4c3d9/doc.md#using-a-bdd-manager). Quoting the documentation:

> `dd` supports "inline BDD references" via the `@` operator. Each BDD node `u` has an integer representation `int(u)` and a string representation `str(u)`. For example, if the integer representation is `5`, then the string representation is `@5`. These enable you to mention existing BDD nodes in formulas, without the need to expand them as formulas.

A `print(u)` or `str(u)` will show a number prefixed by `@`.

**Comment by moohtuh** [comment]
Thank you for the detailed explanation. But I am dumb enough to ask this last part of the question again.

Will it work if I want these nodes to be multiplied:

I initially assign these variables to the BDD:
Where declaredvariables[0] ='a'
declaredvariables[1]='b'
declaredvariables[2]='c'

Then,

```
declaredvariables[0]=bdd.add_expr(expression)
declaredvariables[1]=bdd.add_expr(expression)
declaredvariables[2]=bdd.add_expr(expression)
```

Then trying to multiply all BDD:

`combined = declaredvariables[0] & declaredvariables[1] & declaredvariables[2]`

From what you have told me it seems it should work.

**Comment by moohtuh** [comment]
Here is the problem why it is not working: 

https://ibb.co/Wv7Vp8q

declaredvariables were assigned ['a','b','c'] to be able to reference the BDD functions later where they would be ANDED together.
But after this step: https://ibb.co/MSjgw2y where each of the BDDs are assigned with the expression the declaredvariables changes to function (Ddnode) instead of the original list.

How do I get around this?

**Comment by johnyf** [comment]
To declare the variables named `'a', 'b', 'c', 'd'`, a call to the method `declare` is needed. For example:

```python
from dd.cudd import BDD

bdd = BDD()
vrs = ['a', 'b', 'c', 'd']  # this is a `list` of strings
bdd.declare(*vrs)
```

To create BDD functions for each of the variables `'a', 'b', 'c', 'd'`, the method `dd.cudd.BDD.add_expr` can be used. For example:

```python
vrs_bdds = list()
for var in vrs:
    vrs_bdds.append(bdd.add_expr(var))
# `vrs_bdds` is a `list` of `dd.cudd.Function` instances
```

This iteration will create a `list` of instances of the class `dd.cudd.Function`, one for each variable in `vrs`. These could be conjoined:

```python
a_and_b_and_c_and_d = vrs_bdds[0] & vrs_bdds[1] & vrs_bdds[2] & vrs_bdds[3]
assert a_and_b_and_c_and_d == bdd.add_expr('a /\ b /\ c /\ d'), bdd.to_expr(a_and_b_and_c_and_d)
```

or equivalently:

```python
conjunction = bdd.true
for u in vrs_bdds:
    conjunction &= u
a_and_b_and_c_and_d = conjunction
```

Another option would be to store the mapping from variable *names* (instances of [`str`](https://docs.python.org/3/library/stdtypes.html#textseq)) to *BDDs* (instances of [`dd.cudd.Function`](https://github.com/tulip-control/dd/blob/f9aa4d1a09c286de769bde17dd92ece63cf4c3d9/dd/cudd.pyx#L1513)) in a dictionary ([`dict`](https://docs.python.org/3/library/stdtypes.html#mapping-types-dict)):

```python
vrs_bdds = dict()
for var in vrs:
    vrs_bdds[var] = bdd.add_expr(var)
```

The BDDs of other Boolean functions of the declared variables `'a', 'b', 'c', 'd'` (those identifiers given to the method `bdd.declare`) can be created by passing a string like `'(~ a /\ ~ b /\ ~ c /\ ~ d) \/ (~ a /\ ~ b /\ ~ c /\ d) \/ (~ a /\ ~ b /\ c /\ ~ d)'` to the method `dd.cudd.BDD.add_expr`. The resulting `dd.cudd.Function` can be stored in some `list` or elsewhere. The `&` operator can then be applied between that value (for example, as an element of a `list`) and the same or other `dd.cudd.Function` instances. For example:

```python
bdd_refs = list()
bdd_refs.append(bdd.add_expr('(~ a /\ ~ b /\ ~ c /\ ~ d) \/ (~ a /\ ~ b /\ ~ c /\ d) \/ (~ a /\ ~ b /\ c /\ ~ d)'))
bdd_refs.append(bdd.add_expr('(a /\ ~ b /\ c /\ ~ d) \/ (~ a /\ b /\ c /\ ~ d)'))

conjunction = bdd_refs[0] & bdd_refs[1]
```

Please note any error messages from Python if something is not working.

**Comment by moohtuh** [comment]
Okay, it is not working. Let me put my code here and explain it. It will be very easy this way.

The following is just for BDD for now. I need to calculate each BDDs for different variables and AND them later and calculate the ANDed BDD too.


```
vrs_bdds = list()
vrs_bdds=['aa','bb','cc']                              # In this case I am naming each of the three BDDs aa,bb,cc
list1=[0000, 0011, 1100]                            # This list is provided by the user input; for each of the list I calculate expressions in totalstring 
for index, items in enumerate (list1):
        totalstring
        vrs_bdds.append(bdd.add_expr(totalstring))
        bdd.vars
        bdd.dump('beforereorder_%s' %items , vrs_bdds)     # For each list1 I need the individual BDDs dumped
        _bdd.reorder(bdd)
        bdd.vars
        bdd.dump('afterreorder_%s' %items ,  vrs_bdds)

aa_and_bb_and_cc = vrs_bdds[0] & vrs_bdds[1] & vrs_bdds[2]        # After all list1 calculation I need all BDD multiplied and PDF dumped 
what should be the root node for dumping the final BDD?
```

Right now I am getting this error:

```
 File "/home/........./anaconda3/lib/python3.7/site-packages/dd-0.5.6-py3.7-linux-x86_64.egg/dd/_copy.py", line 51, in _copy_bdd
    if u == u.bdd.true:
AttributeError: 'str' object has no attribute 'bdd'
```
In this line:

`  bdd.dump('beforereorderps_%s.pdf' % items, vrs_bdds  )`

I think calling the root node in bdd.dump is erroneous.

**Comment by johnyf** [comment]
The assignment `vrs_bdds  = ['aa', 'bb', 'cc']` initializes the variable `vrs_bdds` to be a `list` that contains three strings. Then, the iteration `for index, items in enumerate(list1):` appends instances of `Function` (using `vrs_bdds.append`, which is the method [`list.append`](https://docs.python.org/3/library/stdtypes.html#mutable-sequence-types)). The resulting `list` has the form:

```
['aa', 'bb', 'cc', Function instance]
```

When the method `bdd.dump` is called, `vrs_bdds` contains both strings and a `Function` instance. The error is raised due to the strings, which are not `Function` objects, and so do not have an attribute `bdd`. The error is raised at:

https://github.com/tulip-control/dd/blob/f9aa4d1a09c286de769bde17dd92ece63cf4c3d9/dd/_copy.py#L51

A way to avoid this error is to store in a variable the result of `bdd.add_expr` and pass this to the method `bdd.dump`. For example (the user input in this example is assumed to be directly formulas):

```python
from dd.cudd import BDD

bdd = BDD()
vrs = ['a', 'b', 'c', 'd']
bdd.declare(*vrs)

user_input = [
    '~ a /\ ~ b /\ ~ c /\ ~ d',
    '~ a /\ ~ b /\ c /\ d',
    'a /\ b /\ ~ c /\ ~ d']
bdds_list = list()
for index, formula in enumerate(user_input):
    # create the BDD of `formula`
    u = bdd.add_expr(formula)
    # save PDF before reordering
    filename = 'before_reordering_{i}.pdf'.format(i=index)
    roots = [u]
    bdd.dump(filename, roots)
    bdd.reorder()  # please note that the method `BDD.reorder` can be directly called
    # save PDF after reordering
    filename = 'after_reordering_{i}.pdf'.format(i=index)
    bdd.dump(filename, roots)
    # store the BDD in the `list`-valued variable `bdds_list`
    bdds_list.append(u)

# conjoin the BDDs
conj = bdds_list[0] & bdds_list[1] & bdds_list[2]  # it is possible but not necessary to use `bdd.add_expr` here
filename = 'conjoined_bdd.pdf'
roots = [conj]
bdd.dump(filename, roots)
```

It is possible (but not necessary) to conjoin ("AND") using the method `bdd.add_expr`:

```python
expr = '{p} /\ {q} /\ {r}'.format(p=bdds_list[0], q=bdds_list[1], r=bdds_list[2])
conj = bdd.add_expr(expr)
```

I would recommend using an iteration to conjoin the BDDs, instead of the statement `conj = bdds_list[0] & bdds_list[1] & bdds_list[2]`. For example:

```python
conj = bdd.true
for u in bdds_list:
    conj = conj & u
filename = 'conjoined_bdd.pdf'
roots = [conj]
bdd.dump(filename, roots)
```

In case it would be useful, the variable order can be printed with:

```python
var_order = {var: bdd.level_of_var(var) for var in bdd.vars}
print(var_order)
```

**Comment by moohtuh** [comment]
Great it works now. But there is a different issue. I get the following error:

```
  File "/home/......./anaconda3/lib/python3.7/site-packages/dd-0.5.6-py3.7-linux-x86_64.egg/dd/_parser.py", line 240, in <listcomp>
    operands = [add_ast(x, bdd) for x in t.operands]

RecursionError: maximum recursion depth exceeded
```

When the number of bit strings is more than 10 I start to get this error. For my work, I need to work with a maximum bit of 20.

**Comment by johnyf** [comment]
A workaround for the `RecursionError` due to the recursion depth being exceeded could be to increase the recursion limit. The current value of the limit can be found with (documented [here](https://docs.python.org/library/sys.html#sys.getrecursionlimit)):

```python
import sys

old_recursion_limit = sys.getrecursionlimit()
print(old_recursion_limit)
```

and the recursion limit can be changed with (documented [here](https://docs.python.org/library/sys.html#sys.setrecursionlimit)):

```python
new_recursion_limit = 5000
sys.setrecursionlimit(new_recursion_limit)
```

where `new_recursion_limit` is a suitable value larger than `old_recursion_limit`.

Otherwise a non-recursive version of the function [`dd._parser.add_ast`](https://github.com/tulip-control/dd/blob/master/dd/_parser.py#L207) may avoid the recursion limit error.

**Comment by moohtuh** [comment]
Thanks, I have another problem now.

I have reinstalled everything again but this time I don't seem to see the PDF file. The code runs perfectly but no PDF files are dumped at all. I don't know how to approach this.

**Comment by moohtuh** [comment]
So now there's a different issue.

I have increased the recursion limit. When I increase the number of bit strings to more than 12 I see this error in my console: https://ibb.co/KbtnF1w . Sometimes I see nothing and no dd images (conjoined or anything) gets dumped by the code at all. 

You mentioned there's a non-recursive version of the function which is "dd._parser.add_ast"; with this will I be able to work with higher bit string values? If so please show some examples with the function.

**Comment by johnyf** [comment]
The function `dd._parser.add_ast` is recursive. I commented above (https://github.com/tulip-control/dd/issues/57#issuecomment-654052886) that if a non-recursive implementation of the algorithm that the function `add_ast` implements was available, then it could be used to avoid the `RecursionError`.

The console error mentioned above (https://github.com/tulip-control/dd/issues/57#issuecomment-665824436) may be related to the interface used for running Python. It reads "An error occurred while starting the kernel" and "IPKernelApp", so it relates to the IPython kernel (e.g., `IPKernelApp` appears in [this documentation](https://ipython.readthedocs.io/en/stable/config/options/kernel.html#configtrait-IPKernelApp.auto_create)). Please consider saving the Python code to a file, and then running the file from the command line using `python filename.py`.

**Comment by johnyf** [comment]
Increasing the recursion limit is expected to address this issue. So a non-recursive version of the function `dd._parser.add_ast` is not expected to be implemented in the near future.
