### ISSUE TITLE
Quantifying multi-state reliability with MDDs

### ISSUE THREAD

**Issue by glarange** [tulip-control/dd#74]
This is somewhat complex project (attached), but would appreciate your insights into implementing it with dd.mdd or omega.
[MDD - BDD representation MY.pdf](https://github.com/tulip-control/dd/files/6244305/MDD.-.BDD.representation.MY.pdf)

**Comment by johnyf** [comment]
This is not a `dd` issue, and from the title seems similar to #71, which has already been discussed.
