### ISSUE TITLE
Question: Referencing children node in an MDD

### ISSUE THREAD

**Issue by glarange** [tulip-control/dd#75]
The approach in https://github.com/tulip-control/dd/issues/71#issuecomment-758673613 is the right approach, a recursive function that is analogous to the BDD case. In order to implement this, we need to access the successor node of a given node in the MDD. Whereas in the BDD we accessed the successor nodes as u.low and u.high, how do we access the successor node in the MDD?

**Comment by johnyf** [comment]
By using the attribute `dd.mdd.MDD._succ`.

**Comment by glarange** [comment]
I tried

```
from dd import mdd as _mdd

dvars = dict(
    x=dict(level=0, len=4),
    y=dict(level=1, len=2))
mdd = _mdd.MDD(dvars)
from dd.bdd import BDD

bits = dict(x=0, y0=1, y1=2)
bdd = BDD(bits)
u = bdd.add_expr('x \/ (~ y0 /\ y1)')
bdd.incref(u)

# convert BDD to MDD
ints = dict(
    x=dict(level=1, len=2, bitnames=['x']),
    y=dict(level=0, len=4, bitnames=['y0', 'y1']))
mdd, umap = _mdd.bdd_to_mdd(bdd, ints)
mdd._succ
```

But I don't understand the output `{1: (2, None), 2: (1, 1, -1), 3: (0, 2, 2, -1, 2)}`.

I was expecting the number of successors for each node 1, 2 and 3 to be equal to the number of arcs departing from it. Can you clarify how this attribute works?

**Comment by johnyf** [comment]
The keys of the attribute `dd.mdd.MDD._succ` are nodes, and the values are tuples, with the first element a level, and the other elements references to nodes. The tuples are constructed at:

https://github.com/tulip-control/dd/blob/269e4fc493faeec4f8da46162fb78efa6080b9b7/dd/mdd.py#L196
