### ISSUE TITLE
Question: Recursive function for MDDs

### ISSUE THREAD

**Issue by glarange** [tulip-control/dd#76]
Looking to do a recursive probability function similar to https://github.com/tulip-control/dd/issues/62 ,
but for MDDs. The intended workflow is attached below

[Quant_MDD_Workflow.pdf](https://github.com/tulip-control/dd/files/6296919/Quant_MDD_Workflow.pdf)

Question is: 
Is there a way to build an MDD equivalent to:
```
bdd = BDD()
bdd.declare('x', 'y', 'z', 'w')
u = bdd.add_expr('x /\ y')  
```
There doesn't seem to be an attribute mdd.add_expr -- I tried, unsuccessfully. But is there another way to build an MDD from an expression that isn't converting a BDD into an MDD?

**Comment by johnyf** [comment]
The methods `dd.mdd.MDD.ite` and `dd.mdd.MDD.find_or_add` can be used to build directly MDDs, without converting from a BDD. Currently, a method `dd.mdd.MDD.add_expr` is not implemented.

**Comment by glarange** [comment]
I'm familiar with `case` operator for MDDs and `ite` only for BDDs. But how does `ite` work for MDDs?

**Comment by glarange** [comment]
Ultimately what I am trying to achieve is to implement the following recursive algo (here in pseudocode) which is analogous to https://github.com/tulip-control/dd/issues/62#issuecomment-683173730, but I hope works for MDDs:

```
def Prob(x):
    if (x=0) return 1
    elif (x=1) return 0
    elif memorization table has entry (x,P_x) return P_x
    else 
         # S = successors(x)} = {s_i} #
         #    C_i = connecting arcs x -> s_i = {c_ij} #
        P_x = 0
        for s_i in S:
            P_x = P_x + Prob(s_i)*[sum over C_i: p(x=c_ij)]
        insert_memo_table (x, P_x)
        return P_x
```

**Comment by johnyf** [comment]
Similarly to how `ite` works for BDDs.
