### ISSUE TITLE
Support for pure-Python ZDD implementation.

### ISSUE THREAD

**Issue by marcofavorito** [tulip-control/dd#79]
Hi, I would like to know if support for a pure Python implementation of ZDDs is scheduled in the near future. Thanks.

**Comment by johnyf** [comment]
ZDDs are implemented in the [extension module](https://docs.python.org/3/extending/extending.html) `dd.cudd_zdd`, which is a [Cython](https://cython.org/) [module](https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html) that interfaces to the library CUDD that is written in C. BDDs are implemented in both pure Python and with Cython interfaces to the C implementations in CUDD, Sylvan, and BuDDy.

BDDs are good. When performance is not of interest, then using either BDDs or ZDDs will probably have little difference (unless sets with a particular structure are involved). When performance is of interest, then the C implementations would be used, and both BDDs and ZDDs are available there. So I do not know when a pure-Python implementation of ZDDs will be available.

**Comment by marcofavorito** [comment]
Thanks, I'm currently using CUDD implementation of ZDDs. I need ZDDs for very advanced application, and I need to use them instead of BDDs.
