### ISSUE TITLE
Question: MDD Method that returns the level of a node?

### ISSUE THREAD

**Issue by glarange** [tulip-control/dd#80]
Is there an MDD method that returns the level of a node? For example, below, level of `2`,`3` and `4` is `1` and `5` is `0`?

Thanks,
@Glarange

![MDD](https://user-images.githubusercontent.com/3644658/119566559-44ece380-bd79-11eb-911c-d094c581e948.PNG)

**Comment by johnyf** [comment]
The level of an MDD node `u` can be computed using `mdd._succ[abs(u)][0]`.
