### ISSUE TITLE
Maximum expression length for  autoref.BDD.add_expr()

### ISSUE THREAD

**Issue by grgeorgiev** [tulip-control/dd#82]
Hi there, 
I'm trying to use the autoref module for creating a rather large BDD using add_expr()
I noticed that if my expression exceeds certain length (approx. 100000 characters) my program exits with no exception raised. At the moment I'm not sure if this is the expected behaviour.
So I'm wondering if I'm exceeding any limits and if so, how can I adjust the limits. 
I have already increased the python recursion limit from 1000 to 5000 but that doesn't seem to have an effect. 

Regards
Georgi

**Comment by johnyf** [comment]
The segmentation fault that causes the exit from the Python program (after increasing the recursion limit) is caused by the upper bound on the size of the call stack. The Python program can change the size of the call stack for new threads, and in this way avoid this error. An example of how to increase the call stack size, and handle long expressions using the module `dd.autoref`, is the following (using the function [`threading.stack_size`](https://docs.python.org/3/library/threading.html#threading.stack_size)):

```python
"""How to configure CPython for long `dd` expressions."""
import faulthandler
import sys
import threading
import time

import dd.autoref as _bdd


N = 10**5


def runner():
    """Configure CPython, then run."""
    sys.setrecursionlimit(10**3 * N)
    faulthandler.enable()
    threading.stack_size(N * 4096)
    thread = threading.Thread(
        target=test_long_expressions)
    thread.start()
    thread.join()


def test_long_expressions():
    """Create BDDs from two long expressions."""
    bdd = _bdd.BDD()
    bdd.declare('x')
    expr = 'TRUE'
    # requires increasing the recursion limit
    u = add_long_expression(expr, bdd)
    if u != bdd.true:
        raise AssertionError(u)
    print(
        'success with first expression, '
        f'result: {u!r}')
    expr = 'x'
    # requires both:
    #
    # - increasing the recursion limit
    # - increasing the stack size
    #
    # (otherwise the CPython interpreter
    #  exits with a segmentation fault)
    u = add_long_expression(expr, bdd)
    if u != bdd.var('x'):
        raise AssertionError(u)
    print(
        'success with second expression, '
        f'result: {u!r}')


def add_long_expression(expr, bdd):
    """Add BDD to `bdd`, from `expr`."""
    k = round(N / len(expr))
    long_expr = rf'{expr} /\ ' * k + expr
    print(
        'attempting to add expression that '
        f'contains {len(long_expr)} characters')
    t_before = time.time()
    u = bdd.add_expr(long_expr)
    t_after = time.time()
    dt = t_after - t_before
    print(
        'expression converted '
        f'to BDD in {dt:.2f} seconds')
    return u


if __name__ == '__main__':
    runner()
```

**Comment by grgeorgiev** [comment]
Thanks for the reply. This is a very elegant solution. 
Meanwhile, I just divided the long expression into a set of shorter ones which actually works better in my case.
I think this can be closed now.
