### ISSUE TITLE
Python 3.10

### ISSUE THREAD

**Issue by mvcisback** [tulip-control/dd#85]
Hi,

Is there a timeline in place for publishing a wheel for python 3.10?

**Comment by johnyf** [comment]
Thank you for asking. File `dd-0.5.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` is now on PyPI.

**Comment by mvcisback** [comment]
thanks for the quick turn around! closing and upgrading my projects :)
