### ISSUE TITLE
--install-option does not work anymore in requirements.txt

### ISSUE THREAD

**Issue by danjujan** [tulip-control/dd#91]
`--install-option` was removed in pip 23.1: https://pip.pypa.io/en/stable/news/#id27
Is there currently a supported way to install dd with cudd bindings from a requirements.txt file?

**Comment by slivingston** [comment]
@danjujan There is work-in-progress that updates the installation process accordingly: https://github.com/tulip-control/dd/tree/dev_060#cython-bindings

**Comment by slivingston** [comment]
I do not know when it will be ready for general use and merged into `main` branch.

**Comment by hiddevanesch** [comment]
> @danjujan There is work-in-progress that updates the installation process accordingly: https://github.com/tulip-control/dd/tree/dev_060#cython-bindings

On windows, using `set` instead of `export`, this does not install `dd.cudd`. How can I solve this?

**Comment by slivingston** [comment]
I just confirmed success with the [instructions above](https://github.com/tulip-control/dd/issues/91#issuecomment-2068080055) on Debian 12 (GNU/Linux) with Python 3.11.

@hiddevanesch we should move discussion about Windows to another issue or re-open #68
