### ISSUE TITLE
Fault Tree minimum cut sets using zBDD

### ISSUE THREAD

**Issue by wajdi-b** [tulip-control/dd#92]
Hi all,

I am looking for a way to leverage dd in order to compute the minimum cut sets of a gigantic Fault Tree. Currently my Fault Tree is in a Spark DataFrame in the following format:
```py
    [("TOP", "And", ["E1", "E2"]),
    ("E1", "Or", ["A", "E3"]),
    ("E2", "Or", ["C", "E4"]),
    ("E3", "Or", ["B", "C"]),
    ("E4", "And", ["A", "B"])]
```
Here is a graphical representation of that Fault Tree: 
<img width="500" alt="Screenshot 2024-04-28 at 1 54 14 PM" src="https://github.com/tulip-control/dd/assets/6044855/3f015a1d-2f54-444d-891d-69ba09eb052d">

For the above Fault Tree the minimum cut sets, that is the minimum set of events required to trigger the top event, are: `[['C'], ['B', 'A']]`.

Now I've found a way to transform this FT into a BDD thanks to [this snippet of code](https://github.com/sean-reed/bdd-signatures/blob/master/signatures/trees.py#L35-L89). My current code looks like this:
```py
from signatures.trees import fault_tree_to_bdd

basic_events = ['A', 'C', 'B']
top_gate_name = "TOP"
gates =  [("TOP", "*", ("E1", "E2")),
    ("E1", "+", ("A", "E3")),
    ("E2", "+", ("C", "E4")),
    ("E3", "+", ("B", "C")),
    ("E4", "*", ("A", "B"))]
bdd, root = fault_tree_to_bdd(top_gate_name, gates, basic_events)
```

Now that I have the corresponding BDD, I don't know how I can retrieve these minimum cut sets. Do you have any guidance on how to proceed next?

**Comment by wajdi-b** [comment]
I think what would help solve my use case is to have quine-mccluskey algorithm applicable on dd.cudd_zdd, as it is used to obtain the prime implicants of a BDD and prime implicants represent the minimum cut sets as described p.152-153 [here](https://github.com/tulip-control/dd/files/15156557/Control.systems.robotics.and.manufacturing.series.Nikolaos.Limnios.-.Fault.Trees-ISTE.2007.pdf).

**Comment by slivingston** [comment]
It is not immediately clear to me how to do this. I will explore it more in the next 2 or 3 days. Thanks for giving me the reference book.

**Comment by wajdi-b** [comment]
@johnyf Thanks for the complete example! There's a few things I don't get. First I know nothing about orthotopes and I was expecting prime implicants to be just values not intervals. Maybe I'm on a wrong lead here with prime implicants.

When trying your code with a ZDD instead of a BDD, it fails and tells `No complemented edges for ZDDs in CUDD, only for BDDs.`. Why is that?

I'm starting to doubt my converted Fault Tree is equivalent BDD.
Here's the result I get when running on the converted FT above: 
```
Prime implicants:
{'a_int_C': 1, 'b_int_C': 1, 'a_int_A': 0, 'b_int_A': 1, 'a_int_B': 1, 'b_int_B': 1}
{'a_int_C': 1, 'b_int_C': 1, 'a_int_A': 1, 'b_int_A': 1, 'a_int_B': 0, 'b_int_B': 1}
```
I would read this as the MCS being `[[C, B], [C, A]]` in the context of a FT but I think I'm completely off.

There's another lead that I will try with a truth table using https://github.com/topics/quine-mccluskey-algorithm.

**Comment by wajdi-b** [comment]
Thanks again for the long explanation! I will take the time to understand and reframe my problem. [This](https://github.com/tulip-control/dd/files/15177844/ZBDD_algorithm_features_for_an_efficient_Probabilistic_Safety_Assessment.1.pdf) is what I'm trying to achieve.

**Comment by wajdi-b** [comment]
I've found 2 more recent papers leveraging new techniques, so called ZTDD (ternary decision diagrams).
[1-s2.0-S1738573324000184-main.pdf](https://github.com/tulip-control/dd/files/15180637/1-s2.0-S1738573324000184-main.pdf)
[information-10-00368-v2.pdf](https://github.com/tulip-control/dd/files/15180644/information-10-00368-v2.pdf)

**Comment by iicey** [comment]
This is the code I use to calculate the minimum cut set. If the fault tree has more nodes, the amount of calculation will be larger and the calculation time will be longer. 61 basic events may generate tens of millions of cut sets. Is there any room for optimization in my code?

```python
import time
from functools import wraps

tree = {
    "name": "TOP",
    "event_type": "and",
    "children": [
        {
            "name": "E1",
            "event_type": "or",
            "children": [
                {
                    "name": "E1-A",
                    "event_type": "basic"
                },
                {
                    "name": "E3",
                    "event_type": "or",
                    "children": [
                        {
                            "name": "E3-B",
                            "event_type": "basic",
                        }, {
                            "name": "E3-C",
                            "event_type": "basic",
                        }
                    ]
                }
            ]
        },
        {
            "name": "E2",
            "event_type": "or",
            "children": [
                {
                    "name": "E2-C",
                    "event_type": "basic",
                },
                {
                    "name": "E4",
                    "event_type": "and",
                    "children": [
                        {
                            "name": "E4-A",
                            "event_type": "basic",
                        }, {
                            "name": "E4-B",
                            "event_type": "basic",
                        }
                    ]
                }
            ]
        }
    ]
}


def timer_decorator(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        elapsed_time = end_time - start_time
        print(f"function '{func.__name__}' executed in {elapsed_time:.4f} seconds")
        return result

    return wrapper


def flatten_tree(tree, parent_id=None, current_id=1):
    flat_list = []
    node_id = current_id
    current_id += 1
    flat_list.append({
        'id': node_id,
        'parent_id': parent_id,
        'name': tree['name'],
        'event_type': tree['event_type']
    })
    if 'children' in tree:
        for child in tree['children']:
            child_flat, current_id = flatten_tree(child, node_id, current_id)
            flat_list.extend(child_flat)
    return flat_list, current_id


def convert_to_bdd(bdd, node):
    """将故障树节点转换为BDD表达式"""
    if node['event_type'] == 'basic':
        return bdd.var(node['name'])
    elif node['event_type'] == 'and':
        result = bdd.true
        for child in node['children']:
            result &= convert_to_bdd(bdd, child)
        return result
    elif node['event_type'] == 'or':
        result = bdd.false
        for child in node['children']:
            result |= convert_to_bdd(bdd, child)
        return result
    elif node['event_type'] == 'top':
        result = bdd.false
        for child in node['children']:
            result |= convert_to_bdd(bdd, child)
        return result
    else:
        raise ValueError(f"Unknown event type: {node.event_type}")


def find_all_cut_sets(bdd, event_bdd):
    cut_sets = [cut for cut in bdd.pick_iter(event_bdd)]
    true_sets = [set(var for var, val in cut.items() if val) for cut in cut_sets]
    return true_sets


def filter_minimal_cut_sets(cut_sets):
    """过滤出最小割集"""
    minimal_cut_sets = []
    for cut in cut_sets:
        is_minimal = True
        for existing_cut in cut_sets:
            if existing_cut != cut and existing_cut.issubset(cut):
                is_minimal = False
                break
        if is_minimal:
            minimal_cut_sets.append(cut)
    return minimal_cut_sets


@timer_decorator
def main():
    from dd.autoref import BDD

    nodes = flatten_tree(tree)[0]
    bdd = BDD()
    basic_events = [node['name'] for node in nodes if node['event_type'] == 'basic']
    bdd.declare(*basic_events)
    ctx = convert_to_bdd(bdd, tree)

    all_cut_sets = find_all_cut_sets(bdd, ctx)
    _minimal_cut_sets = filter_minimal_cut_sets(all_cut_sets)
    for cut in _minimal_cut_sets:
        print(cut)

    del bdd


if __name__ == '__main__':
    main()

```
